name: AuctionHouse
version: '${project.version}'
main: me.js.auc.auctionhouse.AuctionHouse
api-version: 1.16
authors: [ j1sk1ss ]
description: Auction house for Potolot craft
website: https://www.youtube.com/c/j1sk1ss
commands:
  shop:
    description: open shop window
    usage: /shop <player_nickname>
  sell:
    description: sell chosen item
    usage: /sell <player_nickname> <price>
  expired:
    description: open expired window
    usage: /expired <player_nickname>
  save:
    description: saves global shop and all player`s expired items
    usage: /save
